apiVersion: apps/v1
kind: Deployment
metadata:
  name: au-manager-geo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: au-manager-geo-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: au-manager-geo-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: au-manager-geo-api
        image: auacr.azurecr.io/au-manager-geo-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: au-manager-geo-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: au-manager-geo-api