name: aumanager-geo-ci-webapp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: .\aumanager-geo

    #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'aumanager-geo/appsettings.json'
      env:
        ServiceDBConnectionString: ${{ secrets.DB_CONNECTION_STRING }}
        AzureAd.Instance: ${{ secrets.AZUREAD_INSTANCE }}
        AzureAd.Domain: ${{ secrets.AZUREAD_DOMAIN }}
        AzureAd.TenantId: ${{ secrets.AZUREAD_TENANTID }}
        AzureAd.ClientId: ${{ secrets.AZUREAD_CLIENTID }}
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Publish
      run: dotnet publish -c Release -o aumanager-geo-api-pub
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Selecting the target Subscription
      run: az account set -s "${{ secrets.SUBSCRIPTION_ID }}"
      
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: au-manager-geo
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: .\aumanager-geo-api-pub
